name: fork-win-build

on:
  push:
    branches:
      - 'ci/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    env:
      CARGO_INCREMENTAL: "0"
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: build
        shell: pwsh
        run: |
          $env:PATH = "C:\Strawberry\perl\bin;$env:PATH"
          cargo build --release -p wezterm -p wezterm-gui -p wezterm-mux-server

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wezterm-ime-build
          path: |
            target/release/wezterm.exe
            target/release/wezterm-gui.exe
            target/release/wezterm-mux-server.exe
            assets/windows/**
          if-no-files-found: error
